import { Oleo_Script, Montserrat } from "next/font/google";
import "./globals.css";
import Provider from "../../components/Provider";
import NavBar from "../../components/Navbar/NavBar";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
});

const oleo = Oleo_Script({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-oleo",
});

export const metadata = {
  title: "Abdhulla A - Frontend Developer(React.js)",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` ${montserrat.variable} ${oleo.variable} antialiased`}>
        <Provider>
          <NavBar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
